spring:
  profiles:
    active:
      - cat
      - ES
      - prod
blazej:
  username: YmlUserName
  password: YmlPassword
  jdbcUrl: YmlUrl

---
spring:
  profiles: prod

blazej:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcUrl: YmlProdUrl